name: luminoth
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - click==6.7
  - flask==1.1.1
  - jupyter==1.0.0
  - lxml==4.4.1
  - matplotlib==3.0.3
  - numpy==1.16.4
  - opencv-python==4.1.0.25
  - pandas==0.24.2
  - pillow==6.0.0
  - PyYAML=3.12
  - requests==2.22.0
  - tensorboard==1.12.2
  - tensorflow-gpu==1.12.2
  - tensorflow==1.14.0
  - scikit-image==0.15.0
  - scikit-learn==0.21.2
  - scikit-video==1.1.11
  - scipy==1.3.0
  - pip
  - pip:
    - dm-sonnet==1.23
    - easydict==1.8
    - six==1.12.0

