train:
  debug: True
  # Run name for the training session.
  run_name: frcnn-oct17-alameda-mosquito
  # Directory in which model checkpoints & summaries (for Tensorboard) will be saved.
  job_dir: /data/ai_mosquito_data/jobs_frcnn_oct17_alameda_mosquito/
  learning_rate:
    # Because we're using kwargs, we want the learning_rate dict to be replaced
    # as a whole.
    _replace: True
    # Learning rate decay method ((empty), "none", piecewise_constant, exponential_decay, polynomial_decay)
    # You can define different decay methods using `decay_method` and defining all the necessary arguments.
    decay_method:
    # Oficial initial learning rate is 0.001 (with batch size 32)
    learning_rate: 0.001

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 6
dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir: /data/ai_mosquito_data/tfdata_oct17/
  # Which split of tfrecords to look for.
  split: train
