name: Pytest
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        python-version: ['3.4', '3.6']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools tox tox-gh-actions
          python setup.py install

      # this runs the platform-specific tests declared in tox.ini
      - name: Test with tox
        shell: bash -l {0}
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Send coverage to codecov.io
        shell: bash -l {0}
        run: |
          pip install codecov
          bash <(curl -s https://codecov.io/bash)
