name: Pytest
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        python-version: ['3.6', '3.7']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux libraries
        if: runner.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libxslt1-dev libxml2 libxslt libxml2-dev python-dev
      - name: Install Dependencies with Python ${{ matrix.python-version }}
        shell: bash -l {0}
        run: |
          pip install .
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          conda activate luminoth
          pip install -r requirements.txt
          python setup.py install
          pip install tox
          tox
      - name: Send coverage to codecov.io
        shell: bash -l {0}
        run: |
          pip install codecov
          bash <(curl -s https://codecov.io/bash)
